services:

  service-registry:
    image: 'service-registry:latest'
    container_name: service-registry
    ports:
      - '8081:8081'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
    env_file: .env

  config-server:
    image: 'config-server:latest'
    container_name: config-server
    ports:
      - '8082:8082'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      service-registry:
        condition: service_healthy
    env_file: .env

  gateway:
    image: 'gateway:latest'
    container_name: 'gateway'
    ports:
      - '9090:9090'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway:9090/actuator/health"]
    depends_on:
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
    env_file: .env

  user-service:
    image: 'user-service:latest'
    container_name: 'user-service'
    ports:
      - '8085:8085'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
    depends_on:
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
    env_file: .env

  product-service:
    image: 'product-service:latest'
    container_name: 'product-service'
    ports:
      - '8083:8083'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
    depends_on:
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started
    env_file: .env

  cart-service:
    image: 'cart-service:latest'
    container_name: 'cart-service'
    ports:
      - '8086:8086'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8086/actuator/health']
    depends_on:
      product-service:
        condition: service_healthy
      user-service:
        condition: service_started
    env_file: .env

  order-service:
    image: 'order-service:latest'
    container_name: 'order-service'
    ports:
      - '8084:8084'
    healthcheck:
      test: ["CMD", 'curl', '-f', 'http://localhost:8084/actuator/health']
    depends_on:
      cart-service:
        condition: service_healthy
      user-service:
        condition: service_started
    env_file: .env

  frontend:
    image: 'frontend:latest'
    container_name: 'frontend'
    ports:
      - '8090:80'
    depends_on:
      gateway:
        condition: service_healthy
      order-service:
        condition: service_healthy

  zipkin:
    image: 'openzipkin/zipkin:latest'
    container_name: zipkin
    ports:
      - '9411:9411'