apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_server_url: eureka-lb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_server_url: config-server-svc

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  mysql_url: mysql-svc

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
data:
  frontend_url: https://34.54.201.1.sslip.io
